var projects = [{ // http://www.jsoneditoronline.org/?id=86bed24507b7689237b8eefe9498a69b
  codename : "savanturiers",
  category : "Climatologie",
  organization: "USPC",
  url:"https://www.fun-mooc.fr/courses/USPC/37003/session01/about",
  session: "session01",
  name: "Éducation par la recherche : climatologie à l'École",
  start:"19 janvier 2017",
  end: "20 avril 2017",
  sections: "9",
  learners: "+1400",
  hoursByWeek: "",
  hoursOfShooting:"",
  hoursOfVideos:"",
  html:"",
  sponsor: {
    name : "USPC",
    URL : "",
    budget : ""
  },
  expertsReferents: [{
    family:"Asnour",
    name : "Ange",
    title: "Professeur des écoles, Directrice du programme les Savanturiers l'Ecole de la recherche",
    group: "Savanturiers",
    photoFace: "./Asnour_Ange_ID.png",
    url :  "http://les-savanturiers.cri-paris.org/",
    social: "https://twitter.com/savantures",
    email : "ange.ansour@cri-paris.org"
  }],
  support: {
    name1 : "",
    url1:"",
    name2 : "",
    url2:"",
    name3 : "",
    url3:""
  }
},
            {
  codename : "savanturiersNeuro",
  category : "Neurosciences",
  organization: "USPC",
  url:"https://www.fun-mooc.fr/courses/USPC/37003/session01/about",
  session: "session01",
  name: "Éducation par la recherche : Neurosciences à l'École",
  start:"19 September 2016",
  end: "20 dec 2016",
  sections: "9",
  learners: "+3400",
  hoursByWeek: "",
  hoursOfShooting:"",
  hoursOfVideos:"",
  html:""
}];
var images = [
	{ img: "savanturiers_1.jpg", codename: "savanturiers" },
	{ img: "savanturiers_2.jpg", codename: "savanturiers" },
	{ img: "savanturiers_3.jpg", codename: "savanturiers" },
	{ img: "savanturiers_4.jpg", codename: "savanturiers" },
	{ img: "savanturiers_5.jpg", codename: "savanturiers" },
	{ img: "savanturiers_6.jpg", codename: "savanturiers" },
	{ img: "savanturiers_7.jpg", codename: "savanturiers" },
	{ img: "savanturiers_8.jpg", codename: "savanturiers" },
	{ img: "savanturiers_9.jpg", codename: "savanturiers" },
	{ img: "savanturiers_10.jpg", codename: "savanturiers" },
	{ img: "savanturiers_11.jpg", codename: "savanturiers" },
	{ img: "savanturiers_12.jpg", codename: "savanturiers" },
	{ img: "savanturiers_13.jpg", codename: "savanturiers" },
	{ img: "savanturiers_14.jpg", codename: "savanturiers" },
	{ img: "savanturiers_15.jpg", codename: "savanturiers" },
	{ img: "savanturiers_16.jpg", codename: "savanturiers" },
	{ img: "dtpp_1.jpg", codename: "dtpp" },
	{ img: "dtpp_2.jpg", codename: "dtpp" },
	{ img: "dtpp_3.jpg", codename: "dtpp" },
	{ img: "dtpp_4.jpg", codename: "dtpp" },
	{ img: "dtpp_5.jpg", codename: "dtpp" },
	{ img: "dtpp_6.jpg", codename: "dtpp" },
	{ img: "dtpp_7.jpg", codename: "dtpp" },
	{ img: "dtpp_8.jpg", codename: "dtpp" },
	{ img: "dtpp_9.jpg", codename: "dtpp" },
	{ img: "dtpp_10.jpg", codename: "dtpp" },
	{ img: "dtpp_11.jpg", codename: "dtpp" },
	{ img: "dtpp_12.jpg", codename: "dtpp" },
	{ img: "dtpp_13.jpg", codename: "dtpp" },
	{ img: "dtpp_14.jpg", codename: "dtpp" },
	{ img: "dtpp_15.jpg", codename: "dtpp" },
	{ img: "fab_1.jpg", codename: "fab"},
	{ img: "fab_2.jpg", codename: "fab"},
	{ img: "fab_3.jpg", codename: "fab"},
	{ img: "moocFactory_1.jpg", codename: "moocFactory" },
	{ img: "moocFactory_2.jpg", codename: "moocFactory" },
	{ img: "moocFactory_3.jpg", codename: "moocFactory" },
	{ img: "moocFactory_4.jpg", codename: "moocFactory" },
	{ img: "moocFactory_5.jpg", codename: "moocFactory" },
	{ img: "moocFactory_6.jpg", codename: "moocFactory" },
	{ img: "moocFactory_7.jpg", codename: "moocFactory" },
	{ img: "moocFactory_8.jpg", codename: "moocFactory" },
	{ img: "moocFactory_9.jpg", codename: "moocFactory" },
	{ img: "moocFactory_10.jpg", codename: "moocFactory" },
	{ img: "moocFactory_11.jpg", codename: "moocFactory" },
	{ img: "moocFactory_12.jpg", codename: "moocFactory" },
	{ img: "moocFactory_13.jpg", codename: "moocFactory" },
	{ img: "moocFactory_14.jpg", codename: "moocFactory" },
	{ img: "originesOfLife_1.jpg", codename: "originesOfLife"},
	{ img: "originesOfLife_2.jpg", codename: "originesOfLife"},
	{ img: "originesOfLife_3.jpg", codename: "originesOfLife"},
	{ img: "originesOfLife_4.jpg", codename: "originesOfLife"},
	{ img: "originesOfLife_5.jpg", codename: "originesOfLife"},
	{ img: "originesOfLife_6.jpg", codename: "originesOfLife"},
	{ img: "originesOfLife_7.jpg", codename: "originesOfLife"},
	{ img: "originesOfLife_8.jpg", codename: "originesOfLife"},
	{ img: "originesOfLife_9.jpg", codename: "originesOfLife"},
	{ img: "smartphonelab_1.jpg", codename: "smartphonelab"},
	{ img: "smartphonelab_2.jpg", codename: "smartphonelab"},
	{ img: "smartphonelab_3.jpg", codename: "smartphonelab"},
	{ img: "smartphonelab_4.jpg", codename: "smartphonelab"},
	{ img: "smartphonelab_5.jpg", codename: "smartphonelab"},
	{ img: "smartphonelab_6.jpg", codename: "smartphonelab"},
	{ img: "smartphonelab_7.jpg", codename: "smartphonelab"},
	{ img: "smartphonelab_8.jpg", codename: "smartphonelab"}
];