var projects = [
{
	codename : "savanturiers",
	category : "Neurosciences",
	organization: "USPC",
	url:"https://www.fun-mooc.fr/courses/USPC/37003/session01/about",
	session: "session01",
	name: "Éducation par la recherche : Neurosciences à l'École",
	start:"19 September 2016",
	end: "20 dec 2016",
	sections: "9",
	learners: "+3400",
	hoursByWeek: "",
	hoursOfShooting:"",
	hoursOfVideos:"",
	html:""
}];
var wall2 = [
	{ img: 'omv2_1.jpg', codename : 'originesOfLife2'},
	{ img: 'omv2_2.jpg', codename : 'originesOfLife2'},
	{ img: 'smartphone1.jpg', codename : 'smartphonelab'},
	{ img: 'smartphone2.jpg', codename : 'smartphonelab'},
	{ img: 'smartphone3.jpg', codename : 'smartphonelab'},
	{ img: 'smartphone4.jpg', codename : 'smartphonelab'},
	{ img: 'sbo1.jpg', codename : 'syntheticBio'},
	{ img: 'sbo2.jpg', codename : 'syntheticBio'},
	{ img: 'sbo3.jpg', codename : 'syntheticBio'},
	{ img: 'sbo4.jpg', codename : 'syntheticBio'},
	{ img: 'dt1.jpg', codename : 'dtpp'},
	{ img: 'dt2.jpg', codename : 'dtpp'},
	{ img: 'dt3.jpg', codename : 'dtpp'},
	{ img: 'dt4.jpg', codename : 'dtpp'},
];
var wall1 = [
	{ img: "savanturiers_1.jpg", codename: "savanturiersClimato" },
	{ img: "savanturiers_2.jpg", codename: "savanturiersClimato" },
	{ img: "savanturiers_3.jpg", codename: "savanturiersClimato" },
	{ img: "savanturiers_4.jpg", codename: "savanturiersClimato" },
	{ img: "savanturiers_5.jpg", codename: "savanturiersClimato" },
	{ img: "savanturiers_6.jpg", codename: "savanturiersClimato" },
	{ img: "savanturiers_7.jpg", codename: "savanturiersClimato" },
	{ img: "savanturiers_8.jpg", codename: "savanturiersClimato" },
	{ img: "savanturiers_9.jpg", codename: "savanturiersClimato" },
	{ img: "savanturiers_10.jpg", codename: "savanturiersClimato" },
	{ img: "savanturiers_11.jpg", codename: "savanturiersClimato" },
	{ img: "savanturiers_12.jpg", codename: "savanturiersClimato" },
	{ img: "savanturiers_13.jpg", codename: "savanturiersClimato" },
	{ img: "savanturiers_14.jpg", codename: "savanturiersClimato" },
	{ img: "savanturiers_15.jpg", codename: "savanturiersClimato" },
	{ img: "savanturiers_16.jpg", codename: "savanturiersClimato" },
	{ img: "dtpp_1.jpg", codename: "dtpp" },
	{ img: "dtpp_2.jpg", codename: "dtpp" },
	{ img: "dtpp_3.jpg", codename: "dtpp" },
	{ img: "dtpp_4.jpg", codename: "dtpp" },
	{ img: "dtpp_5.jpg", codename: "dtpp" },
	{ img: "dtpp_6.jpg", codename: "dtpp" },
	{ img: "dtpp_7.jpg", codename: "dtpp" },
	{ img: "dtpp_8.jpg", codename: "dtpp" },
	{ img: "dtpp_9.jpg", codename: "dtpp" },
	{ img: "dtpp_10.jpg", codename: "dtpp" },
	{ img: "dtpp_11.jpg", codename: "dtpp" },
	{ img: "dtpp_12.jpg", codename: "dtpp" },
	{ img: "dtpp_13.jpg", codename: "dtpp" },
	{ img: "dtpp_14.jpg", codename: "dtpp" },
	{ img: "dtpp_15.jpg", codename: "dtpp" },
	{ img: "fab_1.jpg", codename: "fab"},
	{ img: "fab_2.jpg", codename: "fab"},
	{ img: "fab_3.jpg", codename: "fab"},
	{ img: "moocFactory_1.jpg", codename: "moocFactory" },
	{ img: "moocFactory_2.jpg", codename: "moocFactory" },
	{ img: "moocFactory_3.jpg", codename: "moocFactory" },
	{ img: "moocFactory_4.jpg", codename: "moocFactory" },
	{ img: "moocFactory_5.jpg", codename: "moocFactory" },
	{ img: "moocFactory_6.jpg", codename: "moocFactory" },
	{ img: "moocFactory_7.jpg", codename: "moocFactory" },
	{ img: "moocFactory_8.jpg", codename: "moocFactory" },
	{ img: "moocFactory_9.jpg", codename: "moocFactory" },
	{ img: "moocFactory_10.jpg", codename: "moocFactory" },
	{ img: "moocFactory_11.jpg", codename: "moocFactory" },
	{ img: "moocFactory_12.jpg", codename: "moocFactory" },
	{ img: "moocFactory_13.jpg", codename: "moocFactory" },
	{ img: "moocFactory_14.jpg", codename: "moocFactory" },
	/* { img: "moocFactory_15.jpg", codename: "moocFactory" },
	{ img: "moocFactory_16.jpg", codename: "moocFactory" }, */
	{ img: "originesOfLife_1.jpg", codename: "originesOfLife"},
	{ img: "originesOfLife_2.jpg", codename: "originesOfLife"},
	{ img: "originesOfLife_3.jpg", codename: "originesOfLife"},
	{ img: "originesOfLife_4.jpg", codename: "originesOfLife"},
	{ img: "originesOfLife_5.jpg", codename: "originesOfLife"},
	{ img: "originesOfLife_6.jpg", codename: "originesOfLife"},
	{ img: "originesOfLife_7.jpg", codename: "originesOfLife"},
	{ img: "originesOfLife_8.jpg", codename: "originesOfLife"},
	{ img: "originesOfLife_9.jpg", codename: "originesOfLife"},
	{ img: "smartphonelab_1.jpg", codename: "smartphonelab"},
	{ img: "smartphonelab_2.jpg", codename: "smartphonelab"},
	{ img: "smartphonelab_3.jpg", codename: "smartphonelab"},
	{ img: "smartphonelab_4.jpg", codename: "smartphonelab"},
	{ img: "smartphonelab_5.jpg", codename: "smartphonelab"},
	{ img: "smartphonelab_6.jpg", codename: "smartphonelab"},
	{ img: "smartphonelab_7.jpg", codename: "smartphonelab"},
	{ img: "smartphonelab_8.jpg", codename: "smartphonelab"},
	{ img: "syntheticBio_1.jpg", codename:"syntheticBio"},
	{ img: "syntheticBio_2.jpg", codename:"syntheticBio"},
	{ img: "syntheticBio_3.jpg", codename:"syntheticBio"},
	{ img: "syntheticBio_4.jpg", codename:"syntheticBio"},
	{ img: "syntheticBio_5.jpg", codename:"syntheticBio"},
	{ img: "syntheticBio_6.jpg", codename:"syntheticBio"},
	{ img: "syntheticBio_7.jpg", codename:"syntheticBio"},
	{ img: "syntheticBio_8.jpg", codename:"syntheticBio"},
	{ img: "syntheticBio_9.jpg", codename:"syntheticBio"},
	{ img: "syntheticBio_10.jpg", codename:"syntheticBio"},
	{ img: "syntheticBio_11.jpg", codename:"syntheticBio"},
	{ img: "syntheticBio_12.jpg", codename:"syntheticBio"},
	{ img: "syntheticBio_13.jpg", codename:"syntheticBio"},
	{ img: "syntheticBio_14.jpg", codename:"syntheticBio"},
	{ img: "syntheticBio_15.jpg", codename:"syntheticBio"},
	{ img: "syntheticBio_16.jpg", codename:"syntheticBio"},
	{ img: "syntheticBio_17.jpg", codename:"syntheticBio"},
	{ img: "syntheticBio_18.jpg", codename:"syntheticBio"},
	{ img: "syntheticBio_19.jpg", codename:"syntheticBio"},
	{ img: "syntheticBioProtocols_1.jpg", codename:"syntheticBioProtocols"},
	{ img: "syntheticBioProtocols_2.jpg", codename:"syntheticBioProtocols"},
	{ img: "syntheticBioProtocols_3.jpg", codename:"syntheticBioProtocols"},
	{ img: "syntheticBioProtocols_4.jpg", codename:"syntheticBioProtocols"},
	{ img: "syntheticBioProtocols_5.jpg", codename:"syntheticBioProtocols"},
	{ img: "syntheticBioProtocols_6.jpg", codename:"syntheticBioProtocols"},
	{ img: "syntheticBioProtocols_7.jpg", codename:"syntheticBioProtocols"},
	{ img: "syntheticBioProtocols_8.jpg", codename:"syntheticBioProtocols"},
	{ img: "syntheticBioProtocols_9.jpg", codename:"syntheticBioProtocols"},
	{ img: "syntheticBioProtocols_10.jpg", codename:"syntheticBioProtocols"},
	{ img: "syntheticBioProtocols_11.jpg", codename:"syntheticBioProtocols"},
	{ img: "syntheticBioProtocols_12.jpg", codename:"syntheticBioProtocols"},
	{ img: "syntheticBioProtocols_13.jpg", codename:"syntheticBioProtocols"},
	{ img: "syntheticBioProtocols_14.jpg", codename:"syntheticBioProtocols"}
];
